language: go
sudo: true
env:
  - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/go/pkg/mod
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libflint-dev libmpfr-dev
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
script:
  - (env GO111MODULE=on && cd cmd/csppserver && go build)
  - env GO111MODULE=on golangci-lint run --disable-all --deadline=10m
      --enable=gofmt
      --enable=gosimple
      --enable=unconvert
      --enable=ineffassign
      --enable=govet 
